substitutions:
  name: raspiaudio-muse-luxe-3830c4
  friendly_name: RaspiAudio Muse Luxe
packages:
  raspiaudio.muse-luxe: github://esphome/firmware/media-player/raspiaudio-muse-luxe.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ZgMSoFEa5+myMPExQze+IVpohoAiAzeAs9zTQ8JUmeY=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password