substitutions:
  devicename: "tvkamer-vindriktning"
  friendly_name: vindriktning
  device_description: "vindriktning"
  
esphome:
  name: "tvkamer-vindriktning"
  platform: ESP8266
  board: d1_mini
  comment: ${device_description}

# Insert your SSID and Your PWD after inital setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tk Sensor Es Fallback Hotspot"
    password: "k5ENgI9JJVrO"

# Enable logging
logger:
  logs:
      # Make adc input less verbose
      adc: INFO

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  
# Disable webserver, since we push data over mqtt. Can be useful for 
# diagnostics, but takes up quite some memory
web_server:
  port: 80

# Enable OTA upgrade
ota:
  safe_mode: True
  password: xxxxxxxxxxx

# Example configuration entry
uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "${devicename}-PM 2.5µm"
